spring:
  application:
    name: PictureSharingNetwork
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3308/picture_sharing_network?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username: root
    password: 2308
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  servlet:
    context-path: /api/v1/