spring:
  application:
    name: PictureSharingNetwork
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3308/picture_sharing_network?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          trust: "*"
        auth: false
        starttls:
          enable: false
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8088
jwt:
  expiration: 2592000
  expiration-refresh-token: 5184000
  secret-key: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
api:
  prefix: api/v1
application:
  contact: hdh23.work@gmail.com
  font-end:
    confirmation-url: http://localhost:4200/activate-account
